opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - trailing_closure
  - unneeded_parentheses_in_closure_argument

disabled_rules:
  - fallthrough
  - function_parameter_count
  - large_tuple
  - nesting
  - notification_center_detachment
  - operator_whitespace
  - unused_optional_binding
  - trailing_comma
  - trailing_whitespace
  - vertical_parameter_alignment

line_length:
  warning: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

type_name:
  min_length: 1
  max_length:
    warning: 50
    error: 60

identifier_name:
  min_length:
    error: 3
  max_length:
    error: 40
  excluded:
    - id
    - Id
    - on
    - ok
    - to
    - i
    - j
    - k
    - x
    - y
    - z

excluded:
- Pods
- Tests
- Screenshots
